import pyautogui,sys
import time
def inicio():
    #entro al juego
    pyautogui.moveTo(401,310)
    pyautogui.moveTo(236,212)
    pyautogui.click(button='right')
    pyautogui.moveTo(236,188,0.2)
    pyautogui.click(button='left')
    #time.sleep(4)
    #abro la puerta
    pyautogui.moveTo(401,310,4)
    pyautogui.moveTo(422,281)
    pyautogui.click(button='right')
    pyautogui.moveTo(424,256)
    pyautogui.click(button='left')
    #desplazamiento
    #primera casilla
    pyautogui.moveTo(482,260,0.8)
    pyautogui.click(button='right')
    pyautogui.moveTo(482,233)
    pyautogui.click(button='left')
    #desplazamiento
    #segunda casilla(up)
    pyautogui.moveTo(480,267,1.4)
    pyautogui.click(button='right')
    pyautogui.moveTo(478,244)
    pyautogui.click(button='left')
    #tercera casilla(der)
    pyautogui.moveTo(447,322,1.4)
    pyautogui.click(button='right')
    pyautogui.moveTo(452,294)
    pyautogui.click(button='left')
    #cuarta casilla(izq)
    pyautogui.moveTo(368,283,1.2)
    pyautogui.click(button='right')
    pyautogui.moveTo(371,255)
    pyautogui.click(button='left')
    #gran desplazamiento
    #5 casilla(der)
    pyautogui.moveTo(656,437,1.2)
    pyautogui.click(button='right')
    pyautogui.moveTo(656,405)
    pyautogui.click(button='left')
    pyautogui.moveTo(656,405,1.9)
    #time.sleep(1.9)
def min_der():
    pyautogui.moveTo(440,330,1.4)
    pyautogui.click(button='right')
    pyautogui.moveTo(440,302)
    pyautogui.click(button='left')
def min_izq():
    pyautogui.moveTo(354,285,1.3)
    pyautogui.click(button='right')
    pyautogui.moveTo(354,260,0.2)
    pyautogui.click(button='left')
def min_up():
    pyautogui.moveTo(436,285,1.4)
    pyautogui.click(button='right')
    pyautogui.moveTo(436,260)
    pyautogui.click(button='left')
def min_abj():
    pyautogui.moveTo(354,330,1.3)
    pyautogui.click(button='right')
    pyautogui.moveTo(354,305)
    pyautogui.click(button='left')
def min_der_2c():
    pyautogui.moveTo(482,354,2.12)
    pyautogui.click(button='right')
    pyautogui.moveTo(482,322)
    pyautogui.click(button='left')
def min_abj_2c():
    pyautogui.moveTo(314,348,2.12)
    pyautogui.click(button='right')
    pyautogui.moveTo(314,328)
    pyautogui.click(button='left')



for i in range(2):
    inicio()
    min_izq()
    min_abj()
    min_der_2c()
    min_up()
    min_izq()
    min_abj()
    min_der_2c()
    min_up()
    min_abj()
    min_der_2c()
    min_up()
    min_abj()
    min_abj_2c()
    min_der()
    min_abj_2c()
    min_der()
    min_abj_2c()
    min_der()
    min_izq()
    min_abj_2c()
    min_der()
    min_abj_2c()
    min_der()
    min_izq()
    pyautogui.moveTo(401,310,7)
