import pyautogui
import time

#entro al juego
pyautogui.moveTo(401,310)
pyautogui.moveTo(236,212)
pyautogui.click(button='right')
pyautogui.moveTo(236,188)
pyautogui.click(button='left')
time.sleep(4)
#abro la puerta
pyautogui.moveTo(401,310)
pyautogui.moveTo(422,281)
pyautogui.click(button='right')
pyautogui.moveTo(424,256)
pyautogui.click(button='left')
#desplazamiento
#primera casilla
pyautogui.moveTo(482,260,0.8)
pyautogui.click(button='right')
pyautogui.moveTo(482,233)
pyautogui.click(button='left')
#desplazamiento
#segunda casilla(up)
pyautogui.moveTo(480,267,1.4)
pyautogui.click(button='right')
pyautogui.moveTo(478,244)
pyautogui.click(button='left')
#tercera casilla(der)
pyautogui.moveTo(447,322,1.3)
pyautogui.click(button='right')
pyautogui.moveTo(452,294)
pyautogui.click(button='left')
#cuarta casilla(izq)
pyautogui.moveTo(368,283,1.1)
pyautogui.click(button='right')
pyautogui.moveTo(371,255)
pyautogui.click(button='left')
#gran desplazamiento
#5 casilla(der)
pyautogui.moveTo(656,437,1.2)
pyautogui.click(button='right')
pyautogui.moveTo(656,405)
pyautogui.click(button='left')
#6 casilla(izq)
pyautogui.moveTo(355,283,3)
pyautogui.click(button='right')
pyautogui.moveTo(359,255)
pyautogui.click(button='left')
#7 casilla(abj)
pyautogui.moveTo(358,326,1.1)
pyautogui.click(button='right')
pyautogui.moveTo(357,298)
pyautogui.click(button='left')
